AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  jwtRsaCustomAuthorizer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::568600977709:role/Auth0Integration'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Environment:
        Variables:
          TOKEN_ISSUER: 'https://samvanroy.eu.auth0.com/'
          AUDIENCE: 'https://SoftwareSecuritySam.es'
          JWKS_URI: 'https://samvanroy.eu.auth0.com/.well-known/jwks.json'
